assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    assets:
        header_js:
            inputs:
                - '%kernel.root_dir%/../vendor/bmatzner/jquery-bundle/Bmatzner/JQueryBundle/Resources/public/js/jquery.min.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap.min.js'
    filters:
        cssrewrite: ~
        scssphp: 
            import_paths: 
              - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/stylesheets/'
              - '%kernel.root_dir%/../vendor/stinger-soft/platform-bundle/Resources/public/scss/'
            apply_to: '\.scss$'