language: php

before_install:
  - composer self-update

install:
  - composer install --prefer-source

php:
  - 5.5
  - 5.6
  - hhvm


script:
  - mkdir -p ./build/logs
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
  - php ./vendor/bin/coveralls -v
